name: prerelease

on:
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha

env:
  CI: true

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 🛠 Install
        run: yarn install
      - name: 📦 Build, Pre release 🎬
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn prerelease
